version: 2.1
description: Creates and updates the CHANGELOG.md file

orbs:
  orb-tools: circleci/orb-tools@9.0.0

workflows:
  sdk:
    jobs:
      -
        orb-tools/publish:
          orb-path: src/sdk.yml
          orb-ref: ory/sdk@dev:${CIRCLE_BRANCH}
          validate: true
  changelog:
    jobs:
      - orb-tools/publish:
          orb-path: src/changelog.yml
          orb-ref: ory/changelog@dev:${CIRCLE_BRANCH}
          validate: true
      - orb-tools/dev-promote-prod-from-git-tag:
          orb-name: ory/changelog
          add-pr-comment: false
