version: 2.1

orbs:
  circleci-cli: circleci/circleci-cli@0.1.8

jobs:
  validate:
    executor: circleci-cli/default
    steps:
      - checkout
      - run: |-
          set -euxo pipefail
          for orb in src/orbs/*.yml; do circleci orb validate $orb; done

workflows:
  test:
    jobs:
      - validate

#workflows:
#  sdk:
#    jobs:
#      -
#        orb-tools/publish:
#          orb-path: src/sdk.yml
#          orb-ref: ory/sdk@dev:${CIRCLE_BRANCH}
#          publish-token-variable: CIRCLECI_DEV_API_TOKEN
#          validate: true
#      - orb-tools/dev-promote-prod-from-git-tag:
#          orb-name: ory/sdk
#          add-pr-comment: false
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore: /.*/
#  changelog:
#    jobs:
#      - orb-tools/publish:
#          orb-path: src/changelog.yml
#          orb-ref: ory/changelog@dev:${CIRCLE_BRANCH}
#          validate: true
#          publish-token-variable: CIRCLECI_DEV_API_TOKEN
#      - orb-tools/dev-promote-prod-from-git-tag:
#          orb-name: ory/changelog
#          add-pr-comment: false
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore: /.*/
