name: 'Prettier'
description: 'Runs prettier with some Ory-specific config'
inputs:
  dir:
    description: Directory to 'cd' into before running prettier
    default: '.'
    required: false
  action:
    description: Action to perform (check or write)
    default: 'check'
    required: false
  target:
    description: Target prettier should check/write
    default: '.'
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ inputs.dir }}
        mkdir -p node_modules/ory-prettier-styles
        tar -xf "$(npm pack ory-prettier-styles)" -C node_modules/ory-prettier-styles --strip-components=1
        npm i -g "prettier@$(jq -r '.devDependencies.prettier' package.json)"
        rm ory-prettier-styles-*.tgz
      shell: bash
    - name: Run prettier ${{ inputs.action }}
      run: |
        cd ${{ inputs.dir }}
        npx prettier --${{ inputs.action }} ${{ inputs.target }}
      shell: bash
