version: 2.1
description: Creates and updates the CHANGELOG.md file

executors:
  default:
    docker:
      -
        image: circleci/ruby:2.5-node

jobs:
  generate:
    executor: default
    parameters:
      gitemail:
        description: The git committer's email
        type: string
        default: aeneas@ory.sh
      gitusername:
        description: The git committer's username
        type: string
        default: aeneasr
      gitauthtoken:
        description: A GitHub API Token
        type: env_var_name
        default: GITHUB_TOKEN
      commitmessage:
        description: The git commit message
        type: string
        default: "docs: Regenerate and update changelog"
    steps:
      - checkout
      - run: |
          if [ "$(git show -s --format=%B | head -n 1)" = "<<parameters.commitmessage>>" ]; then
              circleci-agent step halt
          fi
      - run: gem install github_changelog_generator -v 1.15.0
      - run: sudo npm i -g doctoc
      - restore_cache:
          keys:
            - changelog-v1
      - run: github_changelog_generator -u $CIRCLE_PROJECT_USERNAME -p $CIRCLE_PROJECT_REPONAME -o CHANGELOG.md --token ${<<parameters.gitauthtoken>>} --cache-file /tmp/github_changelog_generator
      - save_cache:
          key: changelog-v1
          paths:
            - "/tmp/github_changelog_generator"
      - run: doctoc CHANGELOG.md
      - run: "sed -i 's/\\*\\*Table of Contents.*/**Table of Contents**/' CHANGELOG.md"
      - run: "sed -i 's/\\*This Change Log was.*/This Change Log was automatically generated/' CHANGELOG.md"
      - run: git config --global user.email "<<parameters.gitemail>>"
      - run: git config --global user.name "<<parameters.gitusername>>"
      - run: git add CHANGELOG.md
      - run: |
          git commit --allow-empty -m "<<parameters.commitmessage>>" -- CHANGELOG.md || true
      - run: git push origin HEAD:$CIRCLE_BRANCH || true

examples:
  changelog:
    description: Generate and commit the changelog
    usage:
      version: 2.1
      orbs:
        changelog: ory/changelog@0.0.0
      workflows:
        generate:
          jobs:
            - changelog/changelog
