name: 'Releaser'
description: 'Release automation action'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        path: current-repo

    - run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"

        (
          cd current-repo
          if [[ ! -e package.json ]]; then
            echo '{"private": true, "version": "0.0.0"}' > package.json
            git add package.json
          else
            echo "package.json exists and needs not be written"
          fi
        )

        echo 'notes='"$(mktemp).md" >> $GITHUB_ENV

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: actions/checkout@v2
      with:
        repository: ory/changelog
        path: changelog
      env:
        CURRENT_TAG: ${{ github.ref_name }}
      run:
        npm --no-git-tag-version version "$CURRENT_TAG"
        (
          cd changelog
          npm i
        )

        npx conventional-changelog-cli@v2.1.1 --config "changelog/index.js" -r 2 -o "$notes"
        if [[ "$OSTYPE" == "darwin"* ]]; then
          sed -i '' '/^# /d' "$notes"
        else
          sed -i '/^# /d' "$notes"
        fi

        npx prettier -w "$notes"
        git reset --hard HEAD

    - uses: goreleaser/goreleaser-action@v2
      with:
        install-only: true
      env:
        GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
    - run: |
        cd current-repo
        goreleaser release --release-header <(cat "$notes") --rm-dist --timeout 60m --parallelism 1

        git add -A
        git stash || true
        git checkout master || true
        git stash pop || true
        git commit -a -m "autogen: update release artifacts" || true
        git pull origin master --rebase || true
        git push origin HEAD:master || true

